use_frameworks!

target 'DBJTypeConverter_Example' do
  pod 'DBJTypeConverter', :path => '../'

  target 'DBJTypeConverter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
